name: Run Python Tests
 
on:
  push:
    branches:
      - mary
  pull_request:
    branches:
      - mary
 
jobs:
  test:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
 
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
 
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
 
      - name: Run BankAccount tests
        run: python -m unittest test_methods.py -v
